# Configuration for RTLA (Real-Time Log Analyzer)

[log_config]
# Define the log sources and their respective configurations
# Example: File-based log source
file_log_path = "/var/log/myapp.log"

# Add more sources as required
# network_log_address = "192.168.1.100:514"

[alert_config]
# Configuration for alert rules

# Example: Define a simple rule for triggering alerts
error_threshold = 5
critical_message_keyword = "CRITICAL"
